version: '3.8'

services:
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_PERSIST_DIRECTORY=/chroma/chroma
      - CHROMA_COLLECTION_NAME=cursor_memory
      - CHROMA_EMBEDDING_MODEL=all-MiniLM-L6-v2
      - CHROMA_CACHE_SIZE=10000
      - CHROMA_MAX_BATCH_SIZE=100
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chroma_data: 