server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: healthcare_portal
      authentication-database: admin
      username: admin
      password: password
  
  security:
    cors:
      allowed-origins: http://localhost:3002
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: Content-Type,Authorization,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers
      allow-credentials: true
      exposed-headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        mongodb:
          include: mongo
          show-details: always

logging:
  level:
    com.healthcare.portal: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.security: INFO 